### ISSUE TITLE
Uploading a photo using Flickr API

### ISSUE THREAD

**Issue by taccons** [codepath/android-rest-client-template#42]
I don't know if this is the right place to ask, but I am trying to upload a photo using the Flickr API and I think I missed something.

According to the [doc](https://www.flickr.com/services/api/upload.api.html), I need to make a POST request to this url : https://up.flickr.com/services/upload/ and sending the photo.

So I did : 
```java
public void uploadPhotos(AsyncHttpResponseHandler handler, Bitmap photo)
    {
        String apiUrl ="https://up.flickr.com/services/upload/";
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        photo.compress(Bitmap.CompressFormat.JPEG, 100, bos);
        byte[] b = bos.toByteArray();
        RequestParams params = new RequestParams("photo=", b);
        client.post(apiUrl, params, handler);
    }
```

But I always get the response : 
**No photo specified**

I think I am missing to set something but I can't find what...
Could you help me?
Thanks!

**Comment by nesquena** [comment]
```
String apiUrl = "http://up.flickr.com/services/upload/";
RequestParams params = new RequestParams();
ByteArrayOutputStream stream = new ByteArrayOutputStream();
bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream);
final byte[] bytes = stream.toByteArray();
params.put("photo", new ByteArrayInputStream(bytes), "image.png");
client.post(apiUrl, params, handler);
```

**Comment by taccons** [comment]
Thank you very much for your quick answer !
I tried your code, but now I get a new error : 
**SSL is required**

Also, could you please explain what I was missing ? Is it the third parameter of the RequestParams ?

**Comment by nesquena** [comment]
The issue was here: `RequestParams params = new RequestParams("photo=", b);`. It's `photo` not `photo=` as the parameter. Can't speak easily to the issue with SSL error.
