### ISSUE TITLE
[Feature Request] Authenticator and AccountManager

### ISSUE THREAD

**Issue by revant** [codepath/android-rest-client-template#57]
This a wonderful client template.

I wish to add AccountManager/AbstractAuthenticator to this template.

How to begin? any guidance?

I had put together AndroidFrappeAuthenticator. 

You can take a look into https://github.com/revant/AndroidFrappeAuthenticator if anything can be used into this template.

it is an OAuth 2 client for authorization grant - bearer_token (access_token/refresh_token) flow

It was primarily hacked up as a client Authenticator for frappe.io server.
You can Add Settings > Accounts  > Frappe Authenticator account.

It initiates webview with the authorize endpoint. Gets bearer token using authorization code and stores it using AccountManager

Once Account is added, account manager always gives valid bearerToken. 
It refreshes the access_token if required using the refresh_token and replaces old expired bearer_token with new valid one. 

If token from server is revoked, it shows sign-in error in notification and asks the user to login again.

**Comment by rogerhu** [comment]
Any changes can be done in: https://github.com/codepath/android-oauth-handler.  Right now it handles mostly OAuth1 but should be able to handle refresh-related work.  We just haven't prioritized it (and feel free to submit a PR for it)
