### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [codepath/android-rest-client-template#62]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by mansya** [comment]
hi sir. how about this offer? are you interested ?

**Comment by hericst** [comment]
hi

yes, I am

Em ter, 7 de mai de 2019 às 03:01, mansyaprime <notifications@github.com>
escreveu:
